["protostar.config"]
protostar_version = "v0.4.2"

["protostar.project"]
libs_path = "lib"

mock_jedi_router = [
    "./src/mocks/mock_jedi_router.cairo",
]
mock_price_oracle = [
    "./src/mocks/mock_price_oracle.cairo",
]

[profile.devnet.protostar.deploy]
gateway-url="http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"